### ISSUE TITLE
Incorporate inactivity script into the continuous listening pipeline

### ISSUE THREAD

**Issue by cehrett** [cehrett/social_media_frame_analysis#19]
Cooper has produced a script that identifies frame-clusters in the frame store that have been inactive for a given period of time. This script should be used to limit which frame-clusters from the frame store are used in the "collapse into frame store" step.

**Comment by Cooper-Taylor** [comment]
Utilized inactive clustering function to separate the frame_store into inactive and active parts. Script works normally with collapsing the active clusters, and then concatenates the inactive clusters back into the frame store to avoid the loss of frame clusters for long term analysis.
